# Generated by Django 5.0.7 on 2024-09-02 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0002_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="autor",
        ),
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(default="images/galactus.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="image",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
