# Generated by Django 5.0.7 on 2024-09-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "freevisual",
            "0003_remove_image_autor_image_description_image_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="password",
            field=models.CharField(default="admin", max_length=200),
        ),
    ]
