# Generated by Django 5.0.7 on 2024-09-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0004_creator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="password",
            field=models.CharField(default="", max_length=200),
        ),
    ]
