# Generated by Django 5.0.7 on 2024-09-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("freevisual", "0005_alter_creator_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="creator_set", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="creator",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="creator",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="creator_permission_set", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="creator",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="creator",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
