# Generated by Django 5.0.7 on 2024-09-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "freevisual",
            "0006_creator_groups_creator_is_active_creator_is_staff_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="username",
            field=models.CharField(default="pep", max_length=200),
        ),
    ]
