# Generated by Django 5.0.7 on 2024-09-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0010_alter_creator_email_alter_creator_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
