# Generated by Django 5.0.7 on 2024-09-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0011_alter_creator_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="username",
            field=models.CharField(default="", max_length=200, unique=True),
        ),
    ]
