# Generated by Django 5.0.7 on 2024-09-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0013_alter_creator_groups_alter_creator_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
