# Generated by Django 5.0.7 on 2024-09-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0015_alter_image_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
