# Generated by Django 5.0.7 on 2024-09-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0016_creator_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="images/galactus.png",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
