# Generated by Django 5.0.7 on 2024-09-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0017_alter_creator_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Provinces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="creator",
            name="brand",
            field=models.ManyToManyField(
                to="freevisual.brand",
                verbose_name="Marcas de herramientas con las que ha trabajado",
            ),
        ),
        migrations.AddField(
            model_name="tools",
            name="brand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="freevisual.brand",
                verbose_name="marca de herramientas",
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="provinces",
            field=models.ManyToManyField(
                to="freevisual.provinces",
                verbose_name="Provincias donde trabaja el creador",
            ),
        ),
    ]
