# Generated by Django 5.0.7 on 2024-09-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0018_brand_provinces_creator_brand_tools_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tools",
            name="model_tool",
            field=models.CharField(default="", max_length=200),
        ),
    ]
