# Generated by Django 5.0.7 on 2024-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0019_tools_model_tool"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Tiene experiencia en"
                    ),
                ),
            ],
        ),
    ]
