# Generated by Django 5.0.7 on 2024-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0020_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="work",
            field=models.ManyToManyField(
                to="freevisual.work", verbose_name="Trabajos que ha realizado"
            ),
        ),
    ]
