# Generated by Django 5.0.7 on 2024-09-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0021_creator_work"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(
                to="freevisual.tags", verbose_name="Etiquetas de la imgen"
            ),
        ),
    ]
