# Generated by Django 5.0.7 on 2024-09-13 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0022_tags_image_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="tagged_creators",
            field=models.ManyToManyField(
                blank=True,
                related_name="tagged_creators",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creadores etiquetados",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
