# Generated by Django 5.0.7 on 2024-09-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0024_tags_is_pro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
