# Generated by Django 5.0.7 on 2024-10-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freevisual", "0025_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="creator",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="images/camera.jfif", null=True, upload_to="images/"
            ),
        ),
    ]
